# Generated by Django 4.2.16 on 2025-12-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
