# Generated by Django 4.2.16 on 2025-12-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_alter_userlogin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='telegram_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='telegram_sent_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='two_fa_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='two_fa_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
